apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pizzaistio
    version: v2
  name: pizzaistio-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzaistio
      version: v2
  template:
    metadata:
      labels:
        app: pizzaistio
        version: v2
    spec:
      containers:
      - image:  172.30.1.1:5000/test/beer:latest
        imagePullPolicy: IfNotPresent
        name: beer
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
