apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: pizzaistio-roule-pizza
spec:
  destination:
    name: pizzaistio.test
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 100
