apiVersion: v1
kind: Service
metadata:
  name: pizzaistio-v2
  labels:
    app: pizzaistio-v2
    version: v2
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: pizzaistio-v2
    version: v2
